---

- name: ensure packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - unattended-upgrade
    - ufw
  #WA for issue with 'Could not get lock /var/lib/dpkg/lock-frontend'
  until: result is not failed
  retries: 5
  delay: 15

- name: security update
  shell: sudo unattended-upgrade -d

- name: enable ufw and allow ssh
  community.general.ufw:
    state: enabled
    rule: limit
    port: ssh
    proto: tcp

- name: configure default policy
  community.general.ufw:
    policy: deny
    direction: in
  with_items:
    - { policy=deny direction=in}
    - { policy=allow direction=out}

- name: allow http/https connections
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    to_port: "{{ item }}"
  with_items:
     - 80
     - 443

- name: enable ufw
  community.general.ufw:
    state: enabled
