---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    privileged: true
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../group_vars
verifier:
  name: ansible
